version: '2.3'
services:
  training:
    image: moono/tf-1.13-gpu:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    user: "2004:2004"
    container_name: "moono_gpu_all"
    volumes:
      - "/mnt/vision-nas/moono/git-repos/stylegan-reproduced:/work-dir"
      - "/mnt/vision-nas/moono/trained_models/stylegan-reproduced:/model-dir"
      - "/mnt/vision-nas/data-sets/stylegan/ffhq-dataset/tfrecords/ffhq:/tfrecord-dir:ro"
    working_dir: "/work-dir"
    command: ["python", "train.py",
              "--model_base_dir", "/model-dir",
              "--tfrecord_dir", "/tfrecord-dir",
              "--my_ram_size_in_gigabytes", "256"
    ]
  watching:
    image: moono/tf-1.13-gpu:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    user: "2004:2004"
    container_name: "moono_tensorboard"
    depends_on:
      - training
    volumes:
      - "/mnt/vision-nas/moono/trained_models/stylegan-reproduced:/model-dir:ro"
    ports:
      - "36006:6006"
    working_dir: "/model-dir"
    command: ["tensorboard", "--logdir", "./"]
